truncate table ssrep.DAIRITEN;
INSERT INTO ssrep.DAIRITEN （DAIRITEN_CD，DAIRI_MEI_K,DAIRI_MEI) VALUES ('1000001','tang01','アイウエオ');
INSERT INTO ssrep.DAIRITEN （DAIRITEN_CD，DAIRI_MEI_K,DAIRI_MEI) VALUES ('1000002','tang02','アイウエオ');
INSERT INTO ssrep.DAIRITEN （DAIRITEN_CD，DAIRI_MEI_K,DAIRI_MEI) VALUES ('1000003','tang03','アイウエオ');